{
 "title": "prometheus node+blackbox",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Probe Success & Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://example.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_duration_seconds{instance=\"https://example.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    },
    {},
    {}
   ]
  },
  {
   "title": "Disk Free %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}